# For Java 8, try this: maven:3.6.0-jdk-8-alpine
FROM maven:3.5.3-jdk-8-alpine as build

# Place working directory on \server
WORKDIR /server

# copy dependency file
COPY .  .

RUN mvn clean verify



FROM maven:3.6.3-jdk-11

WORKDIR /code-analysis

COPY --from=build /server .

RUN  mvn sonar:sonar
